import os
import random
from dotenv import load_dotenv
import google.generativeai as genai
import logging

# Set up logging
logger = logging.getLogger(__name__)

# 1. Load environment variables from .env
load_dotenv()
api_key = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
if not api_key:
    raise ValueError("Set GOOGLE_API_KEY or GEMINI_API_KEY in your .env file")

# 2. Configure the Gemini client
genai.configure(api_key=api_key)
model = genai.GenerativeModel("gemini-2.0-flash")


def generate_script() -> str:
    """Generate a 30–60s One Piece narration script via Gemini."""
    try:
        topics = [
            "Lore Explanation",
            "Theory or Prediction",
            "Fact or Trivia",
            "Character Power Breakdown"
        ]
        topic = random.choice(topics)

        prompt = (
            "You are a creative anime scriptwriter and One Piece expert.\n"
            "Write a concise, high‑energy, 30–60 second script for a YouTube Shorts or Instagram Reel about One Piece.\n"
            "Topic: Character Power Breakdown\n\n"
            "Requirements:\n"
            "- Pure narration only. Do NOT include any sound effect descriptions, music cues, or parenthetical directions.\n"
            "- Fast‑paced, engaging voice‑over tone.\n"
            "- No camera or stage directions—just the lines spoken by the narrator.\n"
            "- End with a teaser or call to action (e.g., “But that’s not all… What’s your favorite power?”).\n"
            "Assume viewers know One Piece casually but explain terms briefly.\n"
            "Length: ~90 words."
        )

        response = model.generate_content(prompt)
        # Get the first candidate from the response
        if response.text:
            return response.text.strip()
        else:
            raise ValueError("No text generated by Gemini API")
    except Exception as e:
        logger.error(f"Error generating script: {str(e)}")
        raise


if __name__ == "__main__":
    script = generate_script()
    print("✅ Script generated:\n")
    print(script)
